export const GET_FLIGHTS = "GET_FLIGHTS";
export const GET_FLIGHTS_SUCCESS = "GET_FLIGHTS_SUCCESS";
export const GET_FLIGHTS_ERROR = "GET_FLIGHTS_ERROR";
export const GET_FLIGHTS_BY_ROUTE = "GET_FLIGHTS_BY_ROUTE";
export const CLEAR_GET_FLIGHTS_BY_ROUTE = "CLEAR_GET_FLIGHTS_BY_ROUTE";
export const GET_CITIES = "GET_CITIES";
export const SORT_PRICE = "SORT_PRICE";
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";



            
