export const GET_FLIGHTS = "GET_FLIGHTS";
export const GET_FLIGHTS_SUCCESS = "GET_FLIGHTS_SUCCESS";
export const GET_FLIGHTS_ERROR = "GET_FLIGHTS_ERROR";
export const GET_FLIGHTS_BY_ROUTE = "GET_FLIGHTS_BY_ROUTE";

